version: 2

updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "tailwindcss"
      - dependency-name: "tailwind-merge"